version: '3.8'

services:

  postgres:
    image: postgres:13.4
    ports:
      - "9432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '500MB'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # PostgresSQL initialization folder, see https://github.com/docker-library/docs/blob/master/postgres/README.md#initialization-scripts
      - ./postgres_init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
